SET foreign_key_checks = 0;

LOAD DATA LOCAL INFILE '/tmp/github__contributions.csv'
REPLACE INTO TABLE `g_contributions` 
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"' ESCAPED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES;

LOAD DATA LOCAL INFILE '/tmp/github__contributors.csv'
REPLACE INTO TABLE `g_contributors` 
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"' ESCAPED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES;

LOAD DATA LOCAL INFILE '/tmp/github__issue_comments.csv'
REPLACE INTO TABLE `g_issue_comments` CHARACTER SET UTF8MB4
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"' ESCAPED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES;

LOAD DATA LOCAL INFILE '/tmp/github__issue_events.csv'
REPLACE INTO TABLE `g_issue_events` 
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"' ESCAPED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES;

LOAD DATA LOCAL INFILE '/tmp/github__issues.csv'
REPLACE INTO TABLE `g_issues` CHARACTER SET UTF8MB4
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"' ESCAPED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES;

LOAD DATA LOCAL INFILE '/tmp/github__languages.csv'
REPLACE INTO TABLE `g_languages` 
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"' ESCAPED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES;

LOAD DATA LOCAL INFILE '/tmp/github__punch_card.csv'
REPLACE INTO TABLE `g_punch_card` 
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"' ESCAPED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES;

LOAD DATA LOCAL INFILE '/tmp/github__repo.csv'
REPLACE INTO TABLE `g_repo` CHARACTER SET UTF8MB4
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"' ESCAPED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES;

LOAD DATA LOCAL INFILE '/tmp/github__stargazers.csv'
REPLACE INTO TABLE `g_stargazers` 
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"' ESCAPED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES;
